apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
    - image: linkloop.dev:9999/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: linkloop.dev:9999/profiles
      context: profiles
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
