apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiles-depl
spec:
  selector:
    matchLabels:
      app: profiles
  template:
    metadata:
      labels:
        app: profiles
    spec:
      containers:
        - name: profiles
          image: linkloop.dev:9999/profiles
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: "mongodb://profiles-mongo-srv:27017/profiles"
            - name: AMQP_URL
              value: "amqp://linkloop:linkloop@rabbitmq-srv:5672"
            - name: MINIO_ENDPOINT
              value: "minio-srv"
            - name: MINIO_PORT
              value: "9000"
            - name: MINIO_ACCESS_KEY
              value: "minio-root-user"
            - name: MINIO_SECRET_KEY
              value: "minio-root-password"
          resources:
            limits:
              memory: "1Gi"
              cpu: "1.0"

---
apiVersion: v1
kind: Service
metadata:
  name: profiles-srv
spec:
  selector:
    app: profiles
  ports:
    - name: profiles
      protocol: TCP
      port: 3000
      targetPort: 3000
